// Auto-generated by LibreLane
module i2c_controller(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input i2c_sda_in,
  output i2c_sda_out_pin_ctrl,
  output i2c_sda_out_pin_ctrl_n,
  input i2c_scl_in,
  input CLK_I,
  input RST_I,
  output[7:0] ADDR_O,
  input[7:0] DAT_I,
  output[7:0] DAT_O,
  output CYC_O,
  output STB_O,
  output WE_O,
  input ACK_I,
  input ERR_I,
  input RTY_I
);
endmodule
