// Auto-generated by LibreLane
module frequency_counter(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input ext_rst_i,
  input RST_I,
  input CLK_I,
  input[7:0] ADDR_I,
  input[7:0] DAT_I,
  input WE_I,
  input CYC_I,
  input STB_I,
  input signal_input,
  output trigger_signal_out,
  output[7:0] DAT_O,
  output ERR_O,
  output RTY_O,
  output ACK_O,
  output[2:0] pga_gain_control,
  output[2:0] bypass_pin_control
);
endmodule
